import numpy as np

#generated by chatgpt
def rrc_pulse(fs, rs, alpha=0.25, span_symbols=12):
    """
    Generate a Root Raised Cosine (RRC) pulse.
    
    fs: sampling frequency
    rs: symbol rate
    alpha: roll-off factor (0..1)
    span_symbols: total length of pulse in symbols
    
    Returns:
        rrc : pulse shaping filter (numpy array)
        t   : time base for the filter
    """
    Ts = 1 / rs                      # symbol period
    t_step = 1 / fs                  # sampling period
    
    # total pulse length in seconds
    t_max = span_symbols * Ts / 2
    
    # time vector (centered at zero)
    t = np.arange(-t_max, t_max + t_step, t_step)
    
    # allocate pulse
    rrc = np.zeros_like(t)

    for i, ti in enumerate(t):
        if abs(ti) < 1e-12:
            # t = 0 special case
            rrc[i] = 1.0 + alpha * (4/np.pi - 1)
        
        elif abs(abs(ti) - Ts/(4*alpha)) < 1e-12:
            # t = ±Ts/(4α) special case
            rrc[i] = (alpha/np.sqrt(2)) * (
                (1 + 2/np.pi) * np.sin(np.pi/(4*alpha)) +
                (1 - 2/np.pi) * np.cos(np.pi/(4*alpha))
            )
        
        else:
            # general case
            numerator = (
                np.sin(np.pi * ti * (1 - alpha) / Ts) +
                4 * alpha * (ti / Ts) *
                np.cos(np.pi * ti * (1 + alpha) / Ts)
            )
            denominator = (
                np.pi * ti * (1 - (4 * alpha * ti / Ts)**2) / Ts
            )
            rrc[i] = numerator / denominator

    # normalize so pulse energy = 1
    rrc /= np.sqrt(np.sum(rrc**2))

    return rrc



